[package]
authors.workspace = true
edition.workspace = true
name = "sqlx-pg-test-template-macros"
repository.workspace = true
version.workspace = true

[dependencies]
proc-macro2 = {workspace = true, default-features = false}
quote.workspace = true
syn.workspace = true

[lib]
proc-macro = true
