[package]
authors.workspace = true
edition.workspace = true
name = "macros"
repository.workspace = true
version.workspace = true

[dependencies]
proc-macro2 = {version = "1", default-features = false}
quote = "1"
run-test.workspace = true
syn = "2"

[lib]
proc-macro = true
