[package]
authors.workspace = true
edition.workspace = true
name = "sqlx-pg-test-template-runner"
repository.workspace = true
version.workspace = true

[dependencies]
sqlx.workspace = true
thiserror.workspace = true
